### ISSUE TITLE
[RFE] Allow to assign key bindings

### ISSUE THREAD

**Issue by keithbowes** [ebuc99/pacman#11]
I think I could play this much better if I could use the vi keys that I'm used to, instead of having to use the arrow keypad.

**Comment by ebuc99** [comment]
You are using vi? Me too. My part of the implementation was coded with vi (or exactly: vim).
Yes we will implement key bindings.

**Comment by p-martin** [comment]
We added support for vi style control for pacman motion as well as in the menu. You should now be able to also use the keys H, J, K, and L.
