### ISSUE TITLE
score up when player passes a level

### ISSUE THREAD

**Issue by farooqkz** [ebuc99/pacman#14]
My idea is increasing score when user passes a level.I'm not sure it's a good idea.

**Comment by ebuc99** [comment]
In my opinion its not a good idea.
On of our goals is to implement a pacman version very close to the original.
And such a scoring is not original.

But, its open source. Fork it and implement your own version.
Feel free to do what you want.

**Comment by farooqkz** [comment]
@ebuc99: Ok. I didn't know about your policy.
