### ISSUE TITLE
Different levels

### ISSUE THREAD

**Issue by farooqkz** [ebuc99/pacman#15]
Hi.
Level 1 or 2 are just the same thing and this makes the game boring.

**Comment by ebuc99** [comment]
Yes, and level 2 and 3 are just same too. And level 144 and level 98, and level 13 and 42.
It's just a clone of the original pacman. And the goal is to be close to the original.  
And yes its boring compared to games like grand theft auto, resident evil 7 or Prey.
But during my childhood it was a block buster.
Fork it, change it, make a more interesting game for you or other people.
