### ISSUE TITLE
Gamepad

### ISSUE THREAD

**Issue by SerdarSaglam** [ebuc99/pacman#18]
hi, i want to play with gamepad, what should i do

**Comment by p-martin** [comment]
Hi, great that you want to play our pacman :-)
What kind of gamepad do you want to use?

**Comment by SerdarSaglam** [comment]
Hi, thank you
clean interface, best pacman game
Steam and emulator games xbox wireless controller works fine
https://github.com/atar-axis/xpadneo all work :) pacman with gamepad not working :(

**Comment by p-martin** [comment]
I just added some basic support for game controllers - at the moment within a separate branch. Unfortunately, I do not own a game controller. So, if you know how to compile the game from source, could you please compile it using the branch "[gamecontroller](https://github.com/ebuc99/pacman/archive/gamecontroller.zip)" and test whether this fits your needs?

If it works as expected, you should be able to use your game controller's directional keypad and the start and back button.
Btw: entering your name into the highscore list via a game controller is not yet implemented. I will have to think a bit about a good solution...

**Comment by SerdarSaglam** [comment]
Thank you so much.
I've finished the installation, I didn't work with Gamepad :(

Installation type:
gamecontroller.zip download and unpack
./configure
make
make install

**Comment by p-martin** [comment]
Seems like game controller events are not propagated to the game by default. Some initialisation has to be done in advance.

I pushed the changed code to the mentioned branch again. Please feel free to give it another try. The link for the new [zipfile](https://github.com/ebuc99/pacman/archive/gamecontroller.zip) is still the same.

**Comment by SerdarSaglam** [comment]
Excellent work.
Very nice running smoothly. Very fun to play now :)
Thank you very big +1:

**Comment by p-martin** [comment]
The gamecontroller branch has been merged into the official source code and has been closed.

You may now also enter your name into the highscore using the directional pad of your game controller:
- up: next character
- down: previous character
- right: add a new character
- left: delete current character
- start: confirm entered name and continue
However, using the keyboard is much faster ;-)

**Comment by SerdarSaglam** [comment]
Very nice, as in old atari halls :)
