### ISSUE TITLE
Add a .desktop file

### ISSUE THREAD

**Issue by jasonmacduffie** [ebuc99/pacman#2]
It would be cool if a simple .desktop file could be included with the distribution. Here is the one I have now:

```
[Desktop Entry]
Name=Pacman (SDL)
Comment=Yet another pacman clone in C/C++ and SDL
Exec=pacman
Icon=pacman
Type=Application
Categories=Game;ArcadeGame;
```

And this is the icon I am using:

![pacman](https://cloud.githubusercontent.com/assets/6655349/12187461/1cf22dde-b57a-11e5-8f58-1c2203c0d1aa.png)

**Comment by ebuc99** [comment]
Thanks for the issue and help Taknamay.
Its now in the master branch.
